version: '3'

vars:
  BINARY: grip
  GRIP_INSTALL_PATH: /usr/local/bin/

tasks:
  tidy:
    cmds:
      - go fmt ./...
      - go mod tidy

  test:
    cmds:
      - go test --cover ./...
      - go mod verify

  build:
    cmds:
      - go mod verify
      - go build -o bin/{{.BINARY}} cmd/main.go

  install:
    cmds:
      - task: build
      - cp bin/{{.BINARY}} {{.GRIP_INSTALL_PATH}}/{{.BINARY}}

  run:
    cmds:
      - task: build
      - ./bin/{{.BINARY}}

  clean:
    cmds:
      - rm -rf bin